# docker-compose.yml
version: "3.8"

services:
  # Core TR-069 ACS service
  genieacs:
    build:
      context: .
      dockerfile: ./genieacs/Dockerfile
    volumes:
      - ./config:/app/config
    environment:
      GENIEACS_MONGODB_CONNECTION_URL: ${GENIEACS_MONGODB_CONNECTION_URL:-mongodb://mongodb:27017/genieacs}
      GENIEACS_REDIS_HOST: ${GENIEACS_REDIS_HOST:-redis}
      GENIEACS_REDIS_PORT: ${GENIEACS_REDIS_PORT:-6379}

  # Northbound API for the GUI
  genieacs-nbi:
    build:
      context: .
      dockerfile: ./genieacs-nbi/Dockerfile
    volumes:
      - ./config:/app/config
    environment:
      GENIEACS_MONGODB_CONNECTION_URL: ${GENIEACS_MONGODB_CONNECTION_URL:-mongodb://mongodb:27017/genieacs}
      GENIEACS_REDIS_HOST: ${GENIEACS_REDIS_HOST:-redis}
      GENIEACS_REDIS_PORT: ${GENIEACS_REDIS_PORT:-6379}

  # File server for firmware images
  genieacs-fs:
    build:
      context: .
      dockerfile: ./genieacs-fs/Dockerfile
    environment:
      GENIEACS_MONGODB_CONNECTION_URL: ${GENIEACS_MONGODB_CONNECTION_URL:-mongodb://mongodb:27017/genieacs}

  # Web GUI
  genieacs-gui:
    build:
      context: .
      dockerfile: ./gui/Dockerfile
    depends_on:
      - genieacs-nbi

  # Optional local databases (Railway provides managed services in production)
  mongodb:
    image: mongo:4.4
    profiles:
      - local-db

  redis:
    image: redis:7.0
    profiles:
      - local-db